// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xTDT0TzEvXygG4peCkfihyz02yBybLg',
    appId: '1:136809931710:web:70e904e9922d3843af4fef',
    messagingSenderId: '136809931710',
    projectId: 'dopaminebox-dd71b',
    authDomain: 'dopaminebox-dd71b.firebaseapp.com',
    databaseURL: 'https://dopaminebox-dd71b-default-rtdb.firebaseio.com',
    storageBucket: 'dopaminebox-dd71b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcvFVX9mOvZyz8Vk9OCcReEwPkZsgzMw',
    appId: '1:136809931710:android:c0c022c0e0a979a3af4fef',
    messagingSenderId: '136809931710',
    projectId: 'dopaminebox-dd71b',
    databaseURL: 'https://dopaminebox-dd71b-default-rtdb.firebaseio.com',
    storageBucket: 'dopaminebox-dd71b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLgzQAKCQapQmUo_7du_dxH3y2dQ21TXg',
    appId: '1:136809931710:ios:bd9c3d366cf45ac5af4fef',
    messagingSenderId: '136809931710',
    projectId: 'dopaminebox-dd71b',
    databaseURL: 'https://dopaminebox-dd71b-default-rtdb.firebaseio.com',
    storageBucket: 'dopaminebox-dd71b.appspot.com',
    iosClientId: '136809931710-h6s5du1vpmqk6mvdgb87i30usmtr2hhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dopamineBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLgzQAKCQapQmUo_7du_dxH3y2dQ21TXg',
    appId: '1:136809931710:ios:bd9c3d366cf45ac5af4fef',
    messagingSenderId: '136809931710',
    projectId: 'dopaminebox-dd71b',
    databaseURL: 'https://dopaminebox-dd71b-default-rtdb.firebaseio.com',
    storageBucket: 'dopaminebox-dd71b.appspot.com',
    iosClientId: '136809931710-h6s5du1vpmqk6mvdgb87i30usmtr2hhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dopamineBox',
  );
}
